class Constantes:
    TABLE_MOTS = "MOTS"
    TABLE_COOCCURENCES = "COOCURRENCES"
    REQUETE_CREATE_TABLE_MOTS = 'CREATE TABLE IF NOT EXISTS '+TABLE_MOTS+' (id NUMBER(10,0) NOT NULL, mot VARCHAR2(50) NOT NULL,CONSTRAINT pk_mot_id PRIMARY KEY (id))'
    REQUETE_CREATE_TABLE_COOCURRENCES  = 'CREATE TABLE IF NOT EXISTS '+TABLE_COOCCURENCES+' (mot1 NUMBER(10,0) NOT NULL,mot2 NUMBER(10,0) NOT NULL,tailleFenetre NUMBER(2,0) NOT NULL,nbCoocurrences NUMBER(20,0) NOT NULL,CONSTRAINT pk_coocurences PRIMARY KEY (mot1, mot2, tailleFenetre),CONSTRAINT fk_mot1_mot FOREIGN KEY (mot1) REFERENCES mots(id),CONSTRAINT fk_mot2_mot FOREIGN KEY (mot2) REFERENCES mots(id))'
    REQUETE_INSERT_COOCCURENCES = 'INSERT (mot1, mot2, taillefenetre, nbcoocurrences) VALUES (:1,:2,:3,:4);'
    
    REQUETE_SELECT_MOTS = "SELECT * FROM MOTS"
    REQUETE_SELECT_COOCCURENCES = "SELECT * FROM COOCURRENCES"
    
    REQUETE_SELECT_AVEC_TAILLEFENETRE = "SELECT * FROM COOCURRENCES WHERE TAILLEFENETRE = :t"
    
    REQUETE_INSERT_MOTS_LISTE = "INSERT INTO MOTS VALUES (:1, :2)"
    REQUETE_INSERT_COOCCURRENCES = 'insert into COOCURRENCES values (:1, :2, :3, :4)'
    
    REQUETE_UPDATE_COOCCURRENCES = 'UPDATE COOCURRENCES SET NBCOOCURRENCES= :1 WHERE MOT1= :2 AND MOT2= :3 AND TAILLEFENETRE= :4'
    
    REQUETE_SELECT_ID_MOTS  = "SELECT id FROM MOTS WHERE MOT= :p"
    
    REQUETE_EFFACER_TABLE_MOTS = "DROP TABLE MOTS CASCADE CONSTRAINTS"
    REQUETE_EFFACER_TABLE_COOCCURRENCES = "DROP TABLE COOCCURRENCES CASCADE CONSTRAINTS"